import { createApp } from "vue";
import "./style.css";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import App from "./App.vue";
import router from "./router/router";
import * as echarts from "echarts";
const app = createApp(App);
app.use(ElementPlus);
app.use(router);
app.config.globalProperties.$echarts = echarts;
app.mount("#app");
